SELECT * FROM v$resource_limit
where resource_name like '%%'
ORDER BY resource_name;

SELECT DECODE(value, NULL, 'PFILE', 'SPFILE') "Init File Type"
     FROM sys.v_$parameter WHERE name = 'spfile';
     
     select * from V$PARAMETER
     
ALTER SYSTEM SET processes = 300 SCOPE=SPFILE;
ALTER SYSTEM SET sessions = 500 SCOPE=SPFILE;
SHUTDOWN IMMEDIATE
STARTUP


drop index scott.T_ORG_I

CREATE INDEX ORALV.T_ORG_I ON ORALV.T_ORG
(NAME)
INDEXTYPE IS CTXSYS.CONTEXT


CREATE INDEX oralv.t_org_i
    ON oralv.t_org (name)
    INDEXTYPE IS CTXSYS.CONTEXT
  
CREATE INDEX scott.LOAD_SPRORG_I 
    ON scott.load_sprorg (name)
    INDEXTYPE IS CTXSYS.CONTEXT;
    

DROP INDEX SCOTT.LOAD_SPRORG_I;

CREATE INDEX SCOTT.LOAD_SPRORG_I ON SCOTT.LOAD_SPRORG
(NAME)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('SYNC')
NOPARALLEL;

SELECT * FROM oralv.t_org
   WHERE CONTAINS ( name, 'ÐÈÖ' ) > 0;



select STATUS from dba_registry where COMP_ID='CONTEXT' and SCHEMA='CTXSYS';


GRANT CTXAPP to oralv;
GRANT EXECUTE ON CTXSYS.CTX_CLS TO oralv;
GRANT EXECUTE ON CTXSYS.CTX_DDL TO oralv;
GRANT EXECUTE ON CTXSYS.CTX_DOC TO oralv;
GRANT EXECUTE ON CTXSYS.CTX_OUTPUT TO oralv;
GRANT EXECUTE ON CTXSYS.CTX_QUERY TO oralv;
GRANT EXECUTE ON CTXSYS.CTX_REPORT TO oralv;
GRANT EXECUTE ON CTXSYS.CTX_THES TO oralv;
GRANT EXECUTE ON CTXSYS.CTX_ULEXER TO oralv;